#!/bin/bash
#
# configure vpn client
# 
# 2019.05.14

cat << EOG >> /rw/config/rc.local
cat << EOF > /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF
EOG


cat << EOG > /home/user/startup
nautilus &
deluge &
firefox &
EOG

chmod +x /home/user/startup

su - user -c "firefox https://iplocation.net/find-ip-address https://addons.mozilla.org/en-US/firefox/addon/umatrix/ https://addons.mozilla.org/en-US/firefox/addon/noscript/ https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/ https://addons.mozilla.org/en-US/firefox/addon/disabled-add-on-fix-57-60/"


