#!/bin/bash
#
# configure client
# 
# 2019.05.14

dconf write /org/gnome/nautilus/preferences/default-folder-viewer "'list-view'"
dconf write /org/gnome/nautilus/list-view/use-tree-view true
dconf write /org/gnome/nautilus/list-view/defualt-zoom-level "'small'"
dconf write /org/gtk/settings/file-chooser/sort-directories-first true
dconf write /org/gtk/settings/file-chooser/expand-folders true

firefox https://addons.mozilla.org/en-US/firefox/addon/umatrix/ https://addons.mozilla.org/en-US/firefox/addon/noscript/ https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/ https://addons.mozilla.org/en-US/firefox/addon/disabled-add-on-fix-57-60/

echo -e "\n\nalias rm='rm -i'" >> ~/.bashrc

# browser.newtabpage.activity-stream.enabled -> FALSE
# browser.disableResetPrompt -> TRUE
# datareporting.policy.firstRunURL
# datareporting.healthreport.uploadEnabled

https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Enterprise_deployment_before_60
https://wiki.mozilla.org/Privacy/Privacy_Task_Force/firefox_about_config_privacy_tweeks
https://gist.github.com/0XDE57/fbd302cef7693e62c769
https://stackoverflow.com/questions/28410049/how-to-disable-firefox-promt-firefox-automatically-sends-some-data-to-mozilla-s


