#!/bin/bash

echo "Printme:"

if [ $# -eq 0 ] ; then 
    echo "ERROR: no files!"
else
    for f in "$@"; do
        echo " - printing - $f"
        lp -d MFCL2710DW -o PageSize=Letter $f
    done
fi

