#!/bin/bash
#
# combine_doublesided
#
# collate two pdf documents where the second is in reverse order
# occurs when scanning multi-page documents with doc feeder
#
# 2019.08.29

declare _outputfilename="$(basename -s .pdf $1)_$(basename -s .pdf $2).pdf"
pdftk A=$1 B=$2 shuffle A Bend-1 output $_outputfilename


