#!/bin/bash

if [ $# -ne 2 ];  then
    echo
    echo "Usage: img2pdf outputResolution fileName"
    echo "   eg: img2pdf 150 bingo.png"
    echo
    exit 1
fi 

OUTPUTRESOLUTION=$1
INPUTFILENAME=$2
OUTPUTFILENAME="$INPUTFILENAME.pdf"

IMAGEDATA=`identify -verbose $INPUTFILENAME | awk 'BEGIN { FS=": " }; /Resolution|Units|Page geometry/ { print $2 }'`
# For example 118.11x118.11 PixelsPerCentimeter 3766x2163+0+0
# collect all data at once since 'identify' takes time to run

# echo "IMAGEDATA: $IMAGEDATA"

INPUTRESOLUTION=`echo $IMAGEDATA | awk '{print $1}' | awk 'BEGIN { FS="x" };{ print $1 }'`
UNITS=`echo $IMAGEDATA | awk '{print $2}'`
INPUTGEOMETRYX=`echo $IMAGEDATA | awk '{print $3}' | awk 'BEGIN { FS="[x+]" };{ print $1 }'`
INPUTGEOMETRYY=`echo $IMAGEDATA | awk '{print $3}' | awk 'BEGIN { FS="[x+]" };{ print $2 }'`

# echo "$INPUTRESOLUTION : $UNITS : $INPUTGEOMETRYX : $INPUTGEOMETRYY"

case "$UNITS" in
    PixelsPerCentimeter)
        INPUTRESOLUTION=`echo "$INPUTRESOLUTION * 2.54" | bc`
        ;;
    PixelsPerInch)
        # leave in inches
        ;;
    *)
        echo "Unknown units: $UNITS"
        exit 1
        ;;
esac

OUTPUTGEOMETRYX=`echo "$INPUTGEOMETRYX * $OUTPUTRESOLUTION / $INPUTRESOLUTION" | bc`
OUTPUTGEOMETRYY=`echo "$INPUTGEOMETRYY * $OUTPUTRESOLUTION / $INPUTRESOLUTION" | bc`
OUTPUTPAGE=$OUTPUTGEOMETRYX"x"$OUTPUTGEOMETRYY

# echo "OUTPUTGEOMETRYX: $OUTPUTGEOMETRYX , OUTPUTGEOMETRYY: $OUTPUTGEOMETRYY"
echo "convert $INPUTFILENAME -units PixelsPerInch -density $OUTPUTRESOLUTION -page $OUTPUTPAGE -compress JPEG -quality 75 $OUTPUTFILENAME"
convert $INPUTFILENAME -resize $OUTPUTPAGE -units PixelsPerInch -density $OUTPUTRESOLUTION -page $OUTPUTPAGE -compress JPEG -quality 75 $OUTPUTFILENAME



