#!/bin/bash
#
# set up firefox for enterprise security/deploment
# Fedora 32
#
# Date: 20210209

FIREFOXETC=/etc/firefox/policies/
FIREFOXDISTRIBUTION=/usr/lib64/firefox/distribution/

mkdir -p $FIREFOXETC
mkdir -p /usr/lib64/firefox/distribution/

cp autoconfig.js $FIREFOXETC
cp firefox.cfg $FIREFOXETC
cp policies.json $FIREFOXDISTRIBUTION



