#!/bin/bash
# https://docs.fedoraproject.org/en-US/quick-docs/installing-skype/

curl -o /etc/yum.repos.d/skype-stable.repo https://repo.skype.com/rpm/stable/skype-stable.repo
dnf install skypeforlinux

