//Global firefox settings
//
// sources:
//  https://github.com/pyllyukko/user.js
//  https://gist.github.com/gamunu/7fbee4e2318fdc080395a7f74cc34fe9
//  https://stackoverflow.com/questions/28410049/how-to-disable-firefox-promt-firefox-automatically-sends-some-data-to-mozilla-s
//  https://gist.github.com/0XDE57/fbd302cef7693e62c769
//

//pref("dom.event.clipboardevents.enabled", false);
//pref("places.history.enabled", false);

pref("browser.aboutHomeSnippets.updateUrL", "");
pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
pref("browser.newtabpage.activity-stream.feeds.section.topstories.options", "");
pref("browser.newtabpage.activity-stream.feeds.snippets", false);
pref("browser.newtabpage.activity-stream.feeds.system.topsites", false);
pref("browser.newtabpage.activity-stream.feeds.system.topstories", false);
pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
pref("browser.newtabpage.activity-stream.feeds.topsites", false);
pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "");
pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);
pref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);
pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
pref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false);
pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
pref("browser.newtabpage.activity-stream.telemetry", false);
pref("browser.newtabpage.enabled", false);
pref("browser.partnerlink.campaign.topsites", "");
pref("browser.ping-centre.telemetry", false);
pref("browser.policies.perUserDir", false);
pref("browser.safebrowsing.downloads.enabled", false);
pref("browser.safebrowsing.enabled", false);
pref("browser.safebrowsing.malware.enabled", false);
pref("browser.safebrowsing.phishing.enabled", false);
pref("browser.selfsupport.url", "");
pref("browser.send_pings", false);
pref("browser.send_pings.require_same_host", true);
pref("browser.startup.homepage", "/etc/firefox/pref/bookmarks.html");
pref("browser.startup.homepage_override.buildID", "");
pref("browser.startup.homepage_override.mstone", "ignore");
pref("browser.startup.page", 0);
pref("browser.tabs.warnOnClose", false);
pref("browser.tabs.warnOnCloseOtherTabs", false);
pref("browser.toolbars.bookmarks.visibility", "never");
pref("browser.urlbar.suggest.topsites", false);
pref("datareporting.healthreport.service.enabled", false);
pref("datareporting.healthreport.service.firstRun", false);
pref("datareporting.healthreport.uploadEnabled", false);
pref("datareporting.policy.dataSubmissionEnabled", false);
pref("datareporting.policy.firstRunURL", false);
pref("datareporting.sessions.current.clean", true);
pref("devtools.onboarding.telemetry.logged", false);
pref("dom.battery.enabled", false);
pref("dom.disable_open_during_load", false); //enable popups
#pref("dom.event.contextmenu.enabled", false); //enable hijacking right click
pref("extensions.pocket.api", "");
pref("extensions.pocket.enabled", false);
pref("extensions.pocket.oAuthConsumerKey", "");
pref("extensions.pocket.site", "");
pref("loop.enabled", false);
pref("media.peerconnection.enabled", false);
pref("network.IDN_show_punycode", true);
pref("network.dns.disablePrefetch", true);
pref("network.http.speculative-parallel-limit", 0);
pref("network.predictor.enabled", false);
pref("network.prefetch-next", false);
pref("network.websocket.enabled", false);
pref("plugins.enumerable_names", "");
pref("privacy.clearOnShutdown.cache", true);
pref("privacy.clearOnShutdown.cookies", true);
pref("privacy.clearOnShutdown.downloads", false);
pref("privacy.clearOnShutdown.formData", false);
pref("privacy.clearOnShutdown.history", true);
pref("privacy.clearOnShutdown.offlineApps", true);
pref("privacy.clearOnShutdown.sessions", true);
pref("privacy.clearOnShutdown.siteSettings", false);
pref("privacy.history.custom", true);
pref("privacy.sanitize.sanitizeOnShutdown", true);
pref("privacy.trackingprotection.enabled", true);
pref("services.sync.clients.lastSync", 0);
pref("services.sync.declinedEngines", "");
pref("services.sync.nextSync", 0);
pref("services.sync.prefs.sync.browser.urlbar.suggest.topsites", false);
pref("services.sync.tabs.lastSync", "0");
pref("signon.autofillForms", false);
pref("signon.generation.enabled", false);
pref("startup.homepage_override_url", "");
pref("startup.homepage_welcome_url", "");
pref("startup.homepage_welcome_url.additional", "");
pref("toolkit.telemetry.archive.enabled", false);
pref("toolkit.telemetry.bhrPing.enabled", false);
pref("toolkit.telemetry.cachedClientID", "");
pref("toolkit.telemetry.enabled", false);
pref("toolkit.telemetry.firstShutdownPing.enabled", false);
pref("toolkit.telemetry.hybridContent.enabled", false);
pref("toolkit.telemetry.newProfilePing.enabled", false);
pref("toolkit.telemetry.reportingpolicy.firstRun", false);
pref("toolkit.telemetry.shutdownPingSender.enabled", false);
pref("toolkit.telemetry.unified", false);
pref("toolkit.telemetry.updatePing.enabled", false);

