#!/bin/bash
####################################################################
# qube_arrange_windows
#
# get list of windows:
#   wmctrl -lx
#   for p in $(xdotool search  --onlyvisible '.*'); do echo $p $(xdotool getwindowname $p) ; done
# get window dimensions: xwininfo
#
# Date: 2020.12.24


get_windowid_xdotool () {
    # get window id using xdotool return in hex
    #   does not seem to work unless window on visible workspace
    #   but changing --onlyvisible will return multiple results
    declare window_name=$1
    declare win_id_decimal
    declare win_id_hex

    win_id_decimal=$(xdotool search --onlyvisible --name "$window_name")
    win_id_hex=$( printf "0x%x\n" $win_id_decimal )

    echo $win_id_hex
}


get_windowid_wmctrl () {
    # get window id using wmctrl return in hex
    declare window_name=$1
    declare win_id_hex

    win_id_hex=$( wmctrl -lx | grep -i -m 1 "$window_name" | cut -f1 -d' ')
    echo $win_id_hex

}

set_window_geom () {
    declare winid=$1
    declare x=$2
    declare y=$3
    declare width=$4
    declare height=$5
    declare workspace=$6
    declare sticky=$7

    wmctrl -i -r $winid -e 0,$2,$3,$4,$5

    if [[ $workspace -ne 0 ]]; then
        wmctrl -i -r $winid -t $workspace
    fi
    if [[ $sticky -ne 0 ]]; then
        wmctrl -i -r $winid -b add,sticky
    fi
}



declare win_id

## microsoft teams
#win_id=$(get_windowid_wmctrl "congy:crx")
#set_window_geom $win_id 0 30 1200 650 0 1

# Slack
win_id=$(get_windowid_wmctrl "slack")
set_window_geom $win_id 0 30 1300 750 0 1

# scrappy browser
win_id=$(get_windowid_xdotool "ublock")
set_window_geom $win_id 100 170 1300 852 0 1

# workflowy
win_id=$(get_windowid_xdotool "workflowy")
set_window_geom $win_id 723 30 900 850 0 1

# vlc
win_id=$(get_windowid_wmctrl "vlc")
set_window_geom $win_id 1183 600 489 355 0 1

## congy terminal
#win_id=$(get_windowid_wmctrl "congy:xfce4-terminal")
#set_window_geom $win_id 938 30 734 459 1 0
#
## congy slack
#win_id=$(get_windowid_wmctrl "congy:slack")
#set_window_geom $win_id 0 200 1300 750 1 0
#
## congy firefox
#win_id=$(get_windowid_wmctrl "congy:Navigator")
#set_window_geom $win_id 250 170 1200 852 1 0
#
## congy gvim
#win_id=$(get_windowid_wmctrl "congy:gvim")
#set_window_geom $win_id 892 104 780 748 1 0
#
## congy remmina
#win_id=$(get_windowid_wmctrl "congy:org.remmina")
#set_window_geom $win_id 1680 30 779 456 1 0

# vpn
declare vpn_qube=$(wmctrl -lx \
    | grep deluge \
    | tr -s ' ' \
    | cut -f3 -d' ' \
    | cut -f1 -d':')

if [[ ! -z $vpn_qube ]]; then
    win_id=$(get_windowid_wmctrl "dom0 VPN")
    set_window_geom $win_id 1680 30 -1 -1 2 0

    win_id=$(get_windowid_wmctrl "$vpn_qube:deluge")
    set_window_geom $win_id 1680 180 1100 600 2 0

    win_id=$(get_windowid_wmctrl "$vpn_qube:nemo")
    set_window_geom $win_id 1894 30 900 600 2 0

    win_id=$(get_windowid_wmctrl "$vpn_qube:Navigator")
    set_window_geom $win_id 2420 30 1170 1020 2 0

fi
