#!/bin/bash

delcare _MONITOR0="DisplayPort-0"
delcare _MONITOR1="DisplayPort-1"
delcare _IMAGEDIRECTORY="/home/coconut/Pictures/background"

set_background () {
    declare _displayport=$1
    declare _workspace=$2
    declare _style=$3
    declare _imagefile=$4

    xfconf-query \
        --channel xfce4-desktop \
        --property "/backdrop/screen0/$_displayport/workspace$_workspace/image-style" \
        --create \
        --type int \
        --set "$_style"

    xfconf-query \
        --channel xfce4-desktop \
        --property "/backdrop/screen0/$_displayport/workspace$_workspace/last-image" \
        --create \
        --type string \
        --set "$_imagefile"
}


echo "XFCE setup"
echo

echo "== Keyboard setup =="

xfconf-query \
    --channel xfce4-keyboard-shortcuts \
    --property "/commands/custom/<Primary><Shift>F12" \
    --create \
    --type string \
    --set "/home/coconut/admin/qube_launcher_launch"

# use windows key for copy/paste
qvm-features dom0 gui-default-secure-copy-sequence 'Mod4-c'
qvm-features dom0 gui-default-secure-paste-sequence 'Mod4-v'


echo "== Display setup =="

# set right/left screens
xfconf-query \
    --channel displays \
    --property "/Default/$_MONITOR0/Position/X" \
    --set 0

xfconf-query \
    --channel displays \
    --property "/Default/$_MONITOR1/Position/X" \
    --set 1680

xfconf-query \
    --channel displays \
    --property /Schemes/Apply \
    --create \
    --type string \
    --set "Default"


# set top panels

# set backgrounds

set_background "monitor$_MONITOR0" 0 6 "$_IMAGEDIRECTORY/waves3.jpg"
set_background "monitor$_MONITOR0" 1 5 "$_IMAGEDIRECTORY/wallpapertip_blue-victorian-wallpaper_482450.jpg"
set_background "monitor$_MONITOR0" 2 3 "$_IMAGEDIRECTORY/green_jungle.jpg"
set_background "monitor$_MONITOR0" 3 2 "$_IMAGEDIRECTORY/double-bubble-dark.png"
set_background "monitor$_MONITOR1" 0 0 "$_IMAGEDIRECTORY/waves3.jpg"
set_background "monitor$_MONITOR1" 1 5 "$_IMAGEDIRECTORY/wallpapertip_blue-victorian-wallpaper_482450.jpg"
set_background "monitor$_MONITOR1" 2 3 "$_IMAGEDIRECTORY/green_jungle.jpg"
set_background "monitor$_MONITOR1" 3 2 "$_IMAGEDIRECTORY/double-bubble-dark.png"


echo
echo "Done."
