#!/bin/bash

set_background () {
    declare _displayport=$1
    declare _workspace=$2
    declare _style=$3
    declare _imagefile=$4

    xfconf-query \
        --channel xfce4-desktop \
        --property "/backdrop/screen0/$_displayport/workspace$_workspace/image-style" \
        --create \
        --type int \
        --set "$_style"

    xfconf-query \
        --channel xfce4-desktop \
        --property "/backdrop/screen0/$_displayport/workspace$_workspace/last-image" \
        --create \
        --type string \
        --set "$_imagefile"
}


echo "XFCE setup"

#setup keyboard
xfconf-query \
    --channel xfce4-keyboard-shortcuts \
    --property "/commands/custom/<Primary><Shift>F12" \
    --create \
    --type string \
    --set "/home/coconut/admin/qube_launcher_launch"

# use windows key for copy/paste
qvm-features dom0 gui-default-secure-copy-sequence 'Mod4-c'
qvm-features dom0 gui-default-secure-paste-sequence 'Mod4-v'

# display
# set right/left screens

# set top panels

# set backgrounds
delcare _IMAGEDIRECTORY="/home/coconut/Pictures/background"

set_background monitorDisplayPort-0 0 6 "$_IMAGEDIRECTORY/waves3.jpg"
set_background monitorDisplayPort-0 1 5 "$_IMAGEDIRECTORY/wallpapertip_blue-victorian-wallpaper_482450.jpg"
set_background monitorDisplayPort-0 2 3 "$_IMAGEDIRECTORY/green_jungle.jpg"
set_background monitorDisplayPort-0 3 2 "$_IMAGEDIRECTORY/double-bubble-dark.png"
set_background monitorDisplayPort-1 0 0 "$_IMAGEDIRECTORY/waves3.jpg"
set_background monitorDisplayPort-1 1 5 "$_IMAGEDIRECTORY/wallpapertip_blue-victorian-wallpaper_482450.jpg"
set_background monitorDisplayPort-1 2 3 "$_IMAGEDIRECTORY/green_jungle.jpg"
set_background monitorDisplayPort-1 3 2 "$_IMAGEDIRECTORY/double-bubble-dark.png"


echo
echo "Done."
