#!/bin/bash

# References
# https://docs.xfce.org/xfce/xfconf/xfconf-query


delcare _MONITOR0="DisplayPort-0"
delcare _MONITOR1="DisplayPort-1"
delcare _IMAGEDIRECTORY="/home/coconut/Pictures/background"

set_background () {
    declare _displayport=$1
    declare _workspace=$2
    declare _style=$3
    declare _imagefile=$4

    xfconf-query \
        --channel xfce4-desktop \
        --property "/backdrop/screen0/$_displayport/workspace$_workspace/image-style" \
        --create \
        --type int \
        --set "$_style"

    xfconf-query \
        --channel xfce4-desktop \
        --property "/backdrop/screen0/$_displayport/workspace$_workspace/last-image" \
        --create \
        --type string \
        --set "$_imagefile"
}


echo "XFCE setup"
echo

echo "== Keyboard setup =="

xfconf-query \
    --channel xfce4-keyboard-shortcuts \
    --property "/commands/custom/<Primary><Shift>F12" \
    --create \
    --type string \
    --set "/home/coconut/admin/qube_launcher_launch"

# use windows key for copy/paste
qvm-features dom0 gui-default-secure-copy-sequence 'Mod4-c'
qvm-features dom0 gui-default-secure-paste-sequence 'Mod4-v'


echo "== Display setup =="

# set right/left screens
xfconf-query \
    --channel displays \
    --property "/Default/$_MONITOR0/Position/X" \
    --set 0

xfconf-query \
    --channel displays \
    --property "/Default/$_MONITOR1/Position/X" \
    --set 1680

xfconf-query \
    --channel displays \
    --property "/Default/$_MONITOR0/Primary" \
    --set true

xfconf-query \
    --channel displays \
    --property /Schemes/Apply \
    --create \
    --type string \
    --set "Default"

# set top panels


/plugins/plugin-1                            applicationsmenu
/plugins/plugin-10                           tasklist
/plugins/plugin-11                           clock
/plugins/plugin-12                           windowmenu
/plugins/plugin-13                           launcher
/plugins/plugin-15                           separator
/plugins/plugin-15/expand                    true
/plugins/plugin-15/style                     0
/plugins/plugin-1/button-icon                start-here-qubes-blue
/plugins/plugin-1/show-button-title          false
/plugins/plugin-2                            actions
/plugins/plugin-20                           screenshooter
/plugins/plugin-3                            windowmenu
/plugins/plugin-4                            pager
/plugins/plugin-5                            clock
/plugins/plugin-6                            systray
/plugins/plugin-6/names-ordered              <<UNSUPPORTED>>
/plugins/plugin-7                            pulseaudio
/plugins/plugin-7/enable-keyboard-shortcuts  true
/plugins/plugin-8                            screenshooter
/plugins/plugin-9                            applicationsmenu
xfconf-query -c xfce4-panel -p "/plugins/plugin-20" --create -t string --set "screenshooter"

[coconut@dom0 admin]$ xfconf-query -c xfce4-panel -p "/panels/panel-1/plugin-ids"
Value is an array with 8 items:

1
3
15
4
5
7
6
2
[coconut@dom0 admin]$ xfconf-query -c xfce4-panel -p "/plugins/plugin-6/names-ordered"
Value is an array with 7 items:

task manager
qui-devices
qui-clipboard
xfce4-power-manager
qui-disk-space
qui-updates
qui-domains
[coconut@dom0 admin]$ xfconf-query -c xfce4-panel -p "/panels/panel-2/plugin-ids"
Value is an array with 3 items:

8
11
10
[coconut@dom0 admin]$ 


# set backgrounds

set_background "monitor$_MONITOR0" 0 6 "$_IMAGEDIRECTORY/waves3.jpg"
set_background "monitor$_MONITOR0" 1 5 "$_IMAGEDIRECTORY/wallpapertip_blue-victorian-wallpaper_482450.jpg"
set_background "monitor$_MONITOR0" 2 3 "$_IMAGEDIRECTORY/green_jungle.jpg"
set_background "monitor$_MONITOR0" 3 2 "$_IMAGEDIRECTORY/double-bubble-dark.png"
set_background "monitor$_MONITOR1" 0 0 "$_IMAGEDIRECTORY/waves3.jpg"
set_background "monitor$_MONITOR1" 1 5 "$_IMAGEDIRECTORY/wallpapertip_blue-victorian-wallpaper_482450.jpg"
set_background "monitor$_MONITOR1" 2 3 "$_IMAGEDIRECTORY/green_jungle.jpg"
set_background "monitor$_MONITOR1" 3 2 "$_IMAGEDIRECTORY/double-bubble-dark.png"


echo
echo "Done."



