#!/bin/bash

# qube_copy_utilities

declare _sourceqube=dev
declare _sourcedir=/home/user/system/admin
declare _destdir=$(dirname "$0")
declare _filelist

: <<'END'
    qube_backup
    qube_sshraid
    qube_blockit
    qube_copy_admin
    qube_hostnames
    qube_launcher
    qube_make_gis
    qube_make_win
    qube_s3vault
    qube_s3vault.secret

    qvm-portfwd-iptables
    config/brother_instructions_mfcl2710dwp.pdf
    config/configure_client
    config/configure_vpn
    config/configure_vpn_client
    config/go_install
    config/linux-brprinter-installer-2.2.1-1.gz
    config/python3_install
    config/vpn.ovpn.secret
    config/vpn-startup
    config/configFirefox/autoconfig.js
    config/configFirefox/configFirefox
    config/configFirefox/firefox.cfg
    config/configFirefox/policies.json
    config/congy/congy.config.secret
    config/congy/group_rdp_congy.remmina.secret
    config/congy/openfortivpn.service
END


read -r -d '' _filelist <<EOF
    qube_admin
    qubes_functions
EOF

for _f in $_filelist; do
    echo $_f
    qvm-run -p \
        $_sourceqube \
        "cat $_sourcedir/$_f" \
        > $_destdir/$_f
done


