#!/bin/bash

# clean & update system

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get clean
sudo apt-get remove
sudo apt-get autoremove

wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list

# mopidy and other installs

sudo apt-get install 
    Mopidy-Iris \
    Mopidy-Local-Images \
    Mopidy-Local-SQLite \
    Mopidy-YouTube \
    git \
    kodi \
    mopidy \
    mopidy-local \ 
    screen \
    sqlite3 \
    vim \
    vlc \


# python / mopidy installs

sudo pip3 install youtube-dl
sudo pip install \
    Mopidy-Mobile \
    Mopidy-YouTube \

sudo adduser mopidy video

# configure autostart kodi
echo $(which kodi) > ~/.config/lxsession/LXDE-pi/autostart
chmod +x ~/.config/lxsession/LXDE-pi/autostart

